import './globals.css'
import Navbar from '../component/navbar';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/component/footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <div className="page-wrapper">
          <Navbar/>
          <main className="main-content">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
